# Final image needs indy
FROM us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2 AS base

FROM kaminomobile/android-platform-30:1 as build
WORKDIR /home/jenkins/harnes
COPY --chown=jenkins:jenkins android/server/ ./
RUN ls -lah
RUN ls -lah ..
RUN mkdir gradle
RUN pwd
RUN df -H
RUN whoami
RUN ./gradlew
RUN ls -lah
RUN pwd
RUN df -H
RUN whoami
RUN ./gradlew assembleDebug -S

FROM base AS final
WORKDIR /
COPY --from=build /app/build/outputs/apk/debug/app-debug.apk .
# ENTRYPOINT ["dotnet", "DotNet.Backchannel.dll"]
